WaterCoolerWorld/Controllers/CoolersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WaterCoolerWorld.Models;

namespace WaterCoolerWorld.Controllers
{
    [Authorize]
    public class CoolersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Coolers
        public ActionResult Index()
        {
            return View(db.Coolers.ToList());
        }

        [AllowAnonymous]
        public ActionResult Bottle()
        {
            var coolers = db.Coolers.Where(c=>c.Categrory==CoolerCatergory.BottleCooler && c.Active).ToList();
            GetImages(coolers);
            return View("BottleSection", coolers);
        }

        [AllowAnonymous]
        public ActionResult Mains()
        {
            var coolers = db.Coolers.Where(c => c.Categrory == CoolerCatergory.MainsCooler && c.Active).ToList();
            GetImages(coolers);
            return View("MainsSection", coolers);
        }

        [AllowAnonymous]
        public ActionResult Coffee()
        {
            var coolers = db.Coolers.Where(c => c.Categrory == CoolerCatergory.CoffeeMachine && c.Active).ToList();
            GetImages(coolers);
            return View("CoffeeSection", coolers);
        }

        private Cooler GetImageForCooler(Cooler cooler)
        {
            var images = db.Images.Where(i => i.CoolerId == cooler.Id).ToList();
            cooler.Image = images.Count > 0 ? images[0] : new WcwImage { Name = "defaultCooler.png" };
            return cooler;
        }

        private void GetImages(List<Cooler> coolers)
        {
            foreach (var cooler in coolers)
            {
                var images = db.Images.Where(i => i.CoolerId == cooler.Id).ToList();
                cooler.Image = images.Count > 0 ? images[0] : new WcwImage { Name = "defaultCooler.png" };
            }
        }

        [AllowAnonymous]
        public ActionResult Cooler(int id)
        {
            var cooler = db.Coolers.First(c => c.Id == id);
            cooler = GetImageForCooler(cooler);
            return View("Item", cooler);
        }

        // GET: Coolers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cooler cooler = db.Coolers.Find(id);
            if (cooler == null)
            {
                return HttpNotFound();
            }
            return View(cooler);
        }

        // GET: Coolers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Coolers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Categrory,ShortDescription,FullDescription,Price,Active")] Cooler cooler)
        {
            if (ModelState.IsValid)
            {
                db.Coolers.Add(cooler);
                db.SaveChanges();
                return RedirectToAction("AddImage", new {id = cooler.Id});
            }

            return View(cooler);
        }

        // GET: Coolers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cooler cooler = db.Coolers.Find(id);
            if (cooler == null)
            {
                return HttpNotFound();
            }
            return View(cooler);
        }

        // POST: Coolers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Id,Name,Categrory,ShortDescription,FullDescription,Price,Active")] Cooler cooler)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cooler).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cooler);
        }

        // GET: Coolers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cooler cooler = db.Coolers.Find(id);
            if (cooler == null)
            {
                return HttpNotFound();
            }
            return View(cooler);
        }

        // POST: Coolers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cooler cooler = db.Coolers.Find(id);
            db.Coolers.Remove(cooler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddImage(int id)
        {
            ViewBag.CoolerId = id;
            return View("~/Views/Images/Add.cshtml", id);
        }

        [HttpPost]
        public ActionResult AddImage(FormCollection form)
        {
            var file = Request.Files["file"];
            var coolerId = Request.Form["coolerId"];
            if (file != null && !string.IsNullOrEmpty(coolerId) && file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                int count = 1;
                while (System.IO.File.Exists(path))
                {
                    fileName = count + fileName;
                    path = Path.Combine(Server.MapPath("~/Images"), fileName);
                    count++;
                }
                
                file.SaveAs(path);
                var image = new WcwImage
                {
                    Name = fileName,
                    CoolerId = Int16.Parse(coolerId)
                };
                db.Images.Add(image);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
           // return RedirectToAction("AddImage", new {id = coolerId});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WaterCoolerWorld/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WaterCoolerWorld.Models;

namespace WaterCoolerWorld.Controllers
{
    public class HomeController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            var testimonials = db.Testimonials.Where(t=>t.Active).ToList();
            return View("Index", testimonials);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [Authorize]
        public ActionResult Admin()
        {
            return View("Admin");
        }
    }
}

WaterCoolerWorld/Controllers/TestimonialsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WaterCoolerWorld.Models;

namespace WaterCoolerWorld.Controllers
{
    public class TestimonialsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Testimonials
        public ActionResult Index()
        {
            return View(db.Testimonials.ToList());
        }

        // GET: Testimonials/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Testimonial testimonial = db.Testimonials.Find(id);
            if (testimonial == null)
            {
                return HttpNotFound();
            }
            return View(testimonial);
        }

        // GET: Testimonials/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Testimonials/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Quote,CustomerName,Active")] Testimonial testimonial)
        {
            if (ModelState.IsValid)
            {
                db.Testimonials.Add(testimonial);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(testimonial);
        }

        // GET: Testimonials/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Testimonial testimonial = db.Testimonials.Find(id);
            if (testimonial == null)
            {
                return HttpNotFound();
            }
            return View(testimonial);
        }

        // POST: Testimonials/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Quote,CustomerName,Active")] Testimonial testimonial)
        {
            if (ModelState.IsValid)
            {
                db.Entry(testimonial).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(testimonial);
        }

        // GET: Testimonials/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Testimonial testimonial = db.Testimonials.Find(id);
            if (testimonial == null)
            {
                return HttpNotFound();
            }
            return View(testimonial);
        }

        // POST: Testimonials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Testimonial testimonial = db.Testimonials.Find(id);
            db.Testimonials.Remove(testimonial);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WaterCoolerWorld/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WaterCoolerWorld/Views/Home/Admin.cshtml
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_Layout_WCW_Admin.cshtml";
}

<hr />
<div class="container">
    <div class="row" style="min-height: 500px; background-color: #fff; padding: 30px;">
        <div class="col-md-12">
            <h2 class="center-block"><span style="border-bottom: 2px solid #00B7EB; padding-right: 10px;">Admin</span></h2>
        </div>
        <div class="col-xs-6" style="margin-bottom: 20px">
            <a href="@Url.Action("Index", "Coolers")">
                <button class="btn btn-info" style="width: 100%; min-height: 200px;"><span class="glyphicon glyphicon-tint" aria-hidden="true"></span> Coolers</button>
            </a>
        </div>
        <div class="col-xs-6" style="margin-bottom: 20px">
            <a href="@Url.Action("Index", "Testimonials")">
                <button class="btn btn-info" style="width: 100%; min-height: 200px;"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Testimonials</button>
            </a>
        </div>
    </div>
    
</div>

WaterCoolerWorld/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
@Html.Partial("_CarouselParital")
<div class="container">
    <div class="row wcw-med-margin-top">
        <div class="col-xs-12">
            <h1 class="wcc-h1 text-center">Contact Us</h1>
            <hr class="hr-blue" />
            <p>
                To try out our superior service please call 02890 313 818 today and arrange a free trial, and see for yourself how Water Cooler World NI can help your business.
            </p>
            <p>
                At Water Cooler World we strive to deliver the best quality products and unrivalled levels of service excellence. Please feel free to contact our staff with any queries or to arrange your no obligation free trial.
            </p>
            <h4 class="subheading">
                <span class="glyphicon glyphicon-envelope"></span> Send Us A Message
            </h4>
        </div>
        <div class="col-sm-8">
            <form>
                <div class="form-group">
                    <label for="Name">Name</label>
                    <input type="text" class="form-control" id="Name" placeholder="Name">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
                </div>
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea type="textarea" class="form-control" id="message" placeholder="Your message..."></textarea>
                </div>
                <button type="submit" class="btn btn-info form-control"><span class="glyphicon glyphicon-envelope"></span> Send</button>
            </form>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-primary wcw-small-margin-top" style="margin-top: 25px;">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="ion-android-system-home"></span> Information</h3>
                </div>
                <div class="panel-body">
                    <address class="no-margin">
                        <strong>Water Cooler World</strong><br /><br />
                        <p><b><span class="glyphicon glyphicon-home"></span> </b>Suite 3 Fountain Centre,<br />Collage Street,<br />Belfast BT1 6ET
                        <p><b><span class="glyphicon glyphicon-phone"></span> </b>02890 313 818
                        <p><b><span class="glyphicon glyphicon-envelope"></span> </b>sales.ni@watercoolerworld.com
                    </address>
                </div>
            </div>
        </div>
    </div>
</div>

WaterCoolerWorld/Views/Home/Index.cshtml
@model IEnumerable<WaterCoolerWorld.Models.Testimonial>
@{
    ViewBag.Title = "Home";
}
@Html.Partial("_CarouselParital")
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h4 class="text-center wcc-welcome">Welcome To</h4>
            <h1 class="wcc-h1 text-center">Water Cooler World</h1>
            <hr class="hr-blue wcw-small-margin-top"/>
            <div class="row wcw-med-margin-top">
                <div class="col-md-6">
                    <p>
                        Our aim at Water Cooler World is to provide a reliable first class service to you in the simplest and most cost effective way. We provide our customers with quality products and unrivalled levels of service excellence.
                        Our water comes from natural springs and is carefully selected by experts and stringently tested before being extracted by environmentally friendly methods.
                    </p>
                    <p>
                        Our aim at Water Cooler World is to provide a reliable first class service to you in the simplest and most cost effective way. We provide our customers with quality products and unrivalled levels of service excellence.
                        Our water comes from natural springs and is carefully selected by experts and stringently tested before being extracted by environmentally friendly methods.
                    </p>
                </div>
                <div class="col-md-6">
                    <img class="img-responsive" src="~/Images/wcw3.jpg"/>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="myCarousel2" class="carousel slide" data-ride="carousel">

    <div class="carousel-inner" role="listbox">
        @{
            var active = "active";
        }
        @foreach (var testimonial in Model)
        {
            <div class="item @active carousel-small-outer">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="carousel-small-caption text-center">
                                <h1 class="text-center"><q>@testimonial.Quote</q></h1>
                                <p class="text-center">@testimonial.CustomerName</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            active = "";
        }
    </div>
      <a class="left carousel-control" href="#myCarousel2" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel2" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->

    <div class="container">
      <div class="row wcw-med-margin-top">              
         <div class="col-sm-12">
           <h1 class="wcc-h1 text-center">Browse Our Products</h1>
          <hr class="hr-blue wcw-small-margin-top"/>    
           <p>Water Cooler World not only offer bottled coolers, they also supply and fit plumbed in systems (Point of Use) and offer a wide and diverse range of products ranging from high-capacity hot/cold water coolers to sports bottles. Water Cooler World has a planned and effective approach to penetrating the industry in all areas; Schools, Offices, Homes, Factories, Building sites - Water Cooler World has products for all of these and more. </p>
           <hr class="hr-blue"/>  
         </div>
           
         <div class="col-sm-6 col-md-3">
             <a href="@Url.Action("Mains", "Coolers")">
                 <div class="item-outer">
                     <img class="center-block indexPage" src="~/Images/link1b.png" />
                     <div class="linkText">
                         Mains Coolers
                     </div>
                 </div>
             </a>            
          </div>                   
          <div class="col-sm-6 col-md-3">
              <a href="@Url.Action("Bottle", "Coolers")">
                  <div class="item-outer">
                      <img class="center-block indexPage" src="~/Images/link2.jpg" />
                      <div class="linkText">
                          Bottle Coolers
                      </div>
                  </div>
              </a>             
          </div>              
         <div class="col-sm-6 col-md-3">
             <a href="@Url.Action("Coffee", "Coolers")">
                 <div class="item-outer">
                     <img class="center-block indexPage" src="~/Images/link3.png" />
                     <div class="linkText">
                         Coffee Machines
                     </div>
                 </div>
             </a>                
          </div>
         <div class="col-sm-6 col-md-3">
             <a href="@Url.Action("Contact", "Home")">
                 <div class="item-outer">
                     <img class="center-block indexPage" src="~/Images/link4.png" />
                     <div class="linkText">
                         Contact Us
                     </div>
                 </div>
             </a>            
          </div>
      </div>
    </div>